<?php

class RciamEnrollerEof extends AppModel
{
  // Define class name for cake
  public $name = "RciamEnrollerEof";
  // Add behaviors
  public $actsAs = array('Containable');
  
  // Association rules from this model to other models
  public $belongsTo = array(
    'CoEnrollmentFlow' => array(
      'foreignKey' => 'co_enrollment_flow_id',
    ),
    'RciamEnroller' => array(
      'foreignKey' => 'rciam_enroller_id',
    ),
  );
  
  // Validation rules for table elements
  public $validate = array(
    'co_enrollment_flow_id' => array(
      'rule' => 'numeric',
      'required' => true,
      'message' => 'An enrollment flow must be provided.',
    ),
    'rciam_enroller_id' => array(
      'rule' => 'numeric',
      'notBlank' => true,
      'message' => 'A Link Enroller config id must be provided.',
    ),
  );
  
  public function afterSave($created, $options = array())
  {
    // TODO: after saving expire the CSRF token manually.
    parent::afterSave($created, $options); // TODO: Change the autogenerated stub
  }
}